name: Build Custom Firmware
on:
  push:
  workflow_dispatch:

env:
  QMK_REPO: vial-kb/vial-qmk
  QMK_BRANCH: vial

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - name: Checkout custom keymaps
      uses: actions/checkout@v4
      # with:
        # fetch-depth: 0
    
    - name: Clone QMK fork
      run: | 
        git clone --no-checkout https://github.com/$QMK_REPO.git --depth 1 --branch $QMK_BRANCH ./qmk_firmware

    - name: Determine & Checkout relevant keyboards
      working-directory: ./qmk_firmware
      run: |
        git config core.sparsecheckout true
        echo "/*\n!/keyboards\n" > .git/info/sparse-checkout
        for kb in $(find ../keyboards -depth -type d |  awk '$0 !~ /keymaps/' | awk -F / 'NF>=p; {p=NF}' |sed 's/..//'); do echo "$kb/*\n" >> .git/info/sparse-checkout; done;
        echo "!/keyboards/**/keymaps\n" >> .git/info/sparse-checkout
        git checkout $QMK_BRANCH --

    - name: Set Up QMK
      working-directory: ./qmk_firmware
      run: |
        qmk setup -y

    - name: Copy keymap
      run: |
        mkdir -p qmk_firmware/keyboards/
        cp -rup ./keyboards/* ./qmk_firmware/keyboards/
        
    - name: Compile Custom Firmware
      working-directory: ./qmk_firmware
      run: |
        make all

    - name: Upload compiled firmware (build artifact)
      uses: actions/upload-artifact@v4
      with:
        name: Firmware Files
        path: |
          ./qmk_firmware/*.hex
          ./qmk_firmware/*.bin
          ./qmk_firmware/*.uf2

    - name: Upload compiled firmware (tagged release)
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./qmk_firmware/*.hex
          ./qmk_firmware/*.bin
          ./qmk_firmware/*.uf2